apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xesite-cache
spec:
  storageClassName: tigris
  resources:
    requests:
      storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
