# fly.toml file generated for xesite on 2023-09-27T19:39:44-04:00

app = "xesite-dev"

vm.cpus = 2
vm.memory = "2GB"

kill_signal = "SIGINT"
kill_timeout = 5

[mounts]
source = "data"
destination = "/data"
initial_size = "4GB"
auto_extend_size_threshold = 80
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "10GB"

#[experimental]
#cmd = ["/bin/sleep", "infinity"]

[[statics]]
url_prefix = "/"
guest_path = "/"
tigris_bucket = "xesite-dev"
index_document = "index.html"

[build]
image = "ghcr.io/xe/site/bin:earthly"

[env]
HOME = "/data"
DATA_DIR = "/data"
GIT_BRANCH = "main"
SITE_URL = "https://xeiaso.net/"
INTERNAL_API_BIND = ":80"

[[services]]
internal_port = 3000
processes = ["app"]
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[services.concurrency]
hard_limit = 300
soft_limit = 250
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
