# fly.toml file generated for xesite-patreon-saasproxy on 2023-09-27T19:47:18-04:00

app = "xesite-patreon-saasproxy"

kill_signal = "SIGINT"
kill_timeout = 5

[mounts]
source = "data"
destination = "/data"

[env]
DATA_DIR = "/data"

[build]
image = "ghcr.io/xe/site/patreon:latest"

[[services]]
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [services.concurrency]
    hard_limit = 300
    soft_limit = 250
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80
