apiVersion: apps/v1
kind: Deployment
metadata:
  name: patreon-saasproxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: patreon-saasproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: patreon-saasproxy
    spec:
      serviceAccountName: xesite-patreon-saasproxy
      containers:
      - name: web
        image: ghcr.io/xe/site/patreon:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: "BIND"
          value: ":8080"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: KUBERNETES_SECRET_NAME
          value: "xesite-patreon-saasproxy-state"
        envFrom:
        - secretRef:
            name: xesite-patreon-saasproxy-creds
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: X-Kubernetes
              value: "Is alright, I guess"
          initialDelaySeconds: 3
          periodSeconds: 3