apiVersion: v1
kind: Service
metadata:
  name: patreon-saasproxy
  labels:
    app.kubernetes.io/name: patreon-saasproxy
spec:
  selector:
    app.kubernetes.io/name: patreon-saasproxy
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
