name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: alrest-xe-site
    steps:
    - uses: actions/checkout@v4

    - name: build essential
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Setup Homebrew cellar cache
      uses: actions/cache@v4
      with:
        path: |
          /home/linuxbrew/.linuxbrew/Cellar
          /home/linuxbrew/.linuxbrew/bin
          /home/linuxbrew/.linuxbrew/etc
          /home/linuxbrew/.linuxbrew/include
          /home/linuxbrew/.linuxbrew/lib
          /home/linuxbrew/.linuxbrew/opt
          /home/linuxbrew/.linuxbrew/sbin
          /home/linuxbrew/.linuxbrew/share
          /home/linuxbrew/.linuxbrew/var
        key: ${{ runner.os }}-homebrew-cellar-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-homebrew-cellar-

    - name: Install Brew dependencies
      run: |
        brew bundle

    - name: Setup Golang caches
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-

    - name: cache deno.land dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json') }}
        restore-keys: ${{ runner.os }}-deno-
        path: |
          /home/runner/.cache/deno

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
